export const tsCompilerOptionsCopyList = [
  "allowJs",
  "allowSyntheticDefaultImports",
  "allowUmdGlobalAccess",
  "allowUnreachableCode",
  "allowUnusedLabels",
  "alwaysStrict",
  // "baseUrl",
  "charset",
  "checkJs",
  "declaration",
  "declarationMap",
  "emitDeclarationOnly",
  // "declarationDir",
  "disableSizeLimit",
  "disableSourceOfProjectReferenceRedirect",
  "disableSolutionSearching",
  "downlevelIteration",
  "emitBOM",
  "emitDecoratorMetadata",
  "experimentalDecorators",
  "forceConsistentCasingInFileNames",
  "importHelpers",
  "importsNotUsedAsValues",
  "inlineSourceMap",
  "inlineSources",
  "isolatedModules",
  "jsx",
  "keyofStringsOnly",
  // "lib",
  "locale",
  // "mapRoot",
  "maxNodeModuleJsDepth",
  "module",
  "moduleResolution",
  "newLine",
  // "noEmit",
  "noEmitHelpers",
  "noEmitOnError",
  "noErrorTruncation",
  "noFallthroughCasesInSwitch",
  "noImplicitAny",
  "noImplicitReturns",
  "noImplicitThis",
  "noStrictGenericChecks",
  "noUnusedLocals",
  "noUnusedParameters",
  "noImplicitUseStrict",
  // "assumeChangesOnlyAffectDirectDependencies",
  "noLib",
  "noResolve",
  // "out",
  // "outDir",
  // "outFile",
  // "paths",
  "preserveConstEnums",
  // "preserveSymlinks",
  // "project",
  "reactNamespace",
  "jsxFactory",
  // "composite",
  // "incremental",
  // "tsBuildInfoFile",
  "removeComments",
  // "rootDir",
  // "rootDirs",
  "skipLibCheck",
  "skipDefaultLibCheck",
  "sourceMap",
  // "sourceRoot",
  "strict",
  "strictFunctionTypes",
  "strictBindCallApply",
  "strictNullChecks",
  "strictPropertyInitialization",
  "stripInternal",
  "suppressExcessPropertyErrors",
  "suppressImplicitAnyIndexErrors",
  "target",
  // "traceResolution",
  "resolveJsonModule",
  // "types",
  // "typeRoots",
  "esModuleInterop",
  "useDefineForClassFields",
];
